// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type ConflictExceptionReason string

const (
	ConflictExceptionReason_INVALID_RULE_STATE ConflictExceptionReason = "INVALID_RULE_STATE"
)

type LockState string

const (
	LockState_locked         LockState = "locked"
	LockState_pending_unlock LockState = "pending_unlock"
	LockState_unlocked       LockState = "unlocked"
)

type ResourceNotFoundExceptionReason string

const (
	ResourceNotFoundExceptionReason_RULE_NOT_FOUND ResourceNotFoundExceptionReason = "RULE_NOT_FOUND"
)

type ResourceType string

const (
	ResourceType_EBS_SNAPSHOT ResourceType = "EBS_SNAPSHOT"
	ResourceType_EC2_IMAGE    ResourceType = "EC2_IMAGE"
)

type RetentionPeriodUnit string

const (
	RetentionPeriodUnit_DAYS RetentionPeriodUnit = "DAYS"
)

type RuleStatus_SDK string

const (
	RuleStatus_SDK_available RuleStatus_SDK = "available"
	RuleStatus_SDK_pending   RuleStatus_SDK = "pending"
)

type ServiceQuotaExceededExceptionReason string

const (
	ServiceQuotaExceededExceptionReason_SERVICE_QUOTA_EXCEEDED ServiceQuotaExceededExceptionReason = "SERVICE_QUOTA_EXCEEDED"
)

type UnlockDelayUnit string

const (
	UnlockDelayUnit_DAYS UnlockDelayUnit = "DAYS"
)

type ValidationExceptionReason string

const (
	ValidationExceptionReason_INVALID_PAGE_TOKEN      ValidationExceptionReason = "INVALID_PAGE_TOKEN"
	ValidationExceptionReason_INVALID_PARAMETER_VALUE ValidationExceptionReason = "INVALID_PARAMETER_VALUE"
)
